name = "idea-home"
main = "worker.ts"
compatibility_date = "2024-09-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "KV"
id = "815c294b7bb74dc1997fb51a914c0d6d"