# ====================================================================
# Cloudflare Worker Configuration: IDEA HOME
# ====================================================================

name = "idea-home-ir"

main = "worker.ts"

compatibility_date = "2024-09-01"


# Static React/Vite build output
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"


# Environment variables
[vars]
ENVIRONMENT = "production"


# Cloudflare KV Storage
[[kv_namespaces]]
binding = "KV"
id = "815c294b7bb74dc1997fb51a914c0d6d"
